WEBG301-ASM-master/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $PurchaseDate;



    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="Orders")
     */
    private $OrderDetail;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Total;

    public function __construct()
    {
        $this->OrderDetail = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getPurchaseDate(): ?\DateTimeInterface
    {
        return $this->PurchaseDate;
    }

    public function setPurchaseDate(\DateTimeInterface $PurchaseDate): self
    {
        $this->PurchaseDate = $PurchaseDate;

        return $this;
    }


    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetail(): Collection
    {
        return $this->OrderDetail;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->OrderDetail->contains($orderDetail)) {
            $this->OrderDetail[] = $orderDetail;
            $orderDetail->setOrders($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->OrderDetail->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrders() === $this) {
                $orderDetail->setOrders(null);
            }
        }

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->Total;
    }

    public function setTotal(?float $Total): self
    {
        $this->Total = $Total;

        return $this;
    }
}

WEBG301-ASM-master/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $Category;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="Product")
     */
    private $orderDetails;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Imgurl;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="products")
     */
    private $Publisher;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setProduct($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getProduct() === $this) {
                $orderDetail->setProduct(null);
            }
        }

        return $this;
    }

    public function getImgurl(): ?string
    {
        return $this->Imgurl;
    }

    public function setImgurl(string $Imgurl): self
    {
        $this->Imgurl = $Imgurl;

        return $this;
    }

    public function getPublisher(): ?User
    {
        return $this->Publisher;
    }

    public function setPublisher(?User $Publisher): self
    {
        $this->Publisher = $Publisher;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

}

WEBG301-ASM-master/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name')
            ->add('Price')
            ->add('Description')
            ->add('Category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'Name'])
            ->add('Image', FileType::class, [
                'label' => 'Product Image',
                'mapped' => false,
                'required' => false,]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

WEBG301-ASM-master/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Order;
use App\Entity\OrderDetail;
use App\Form\ProductType;
use App\Repository\OrderRepository;
use App\Repository\OrderDetailRepository;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Psr\Log\LoggerInterface;


/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/listing/{pageId}", name="app_product_index", methods={"GET"})
     */
    public function index(Request $request,ProductRepository $productRepository,CategoryRepository $categoryRepository,int $pageId = 1): Response
    {           
        $minPrice = $request->query->get('minPrice');
        $maxPrice = $request->query->get('maxPrice');
        $cat = $request->query->get('category');
        $word = $request->query->get('word');
        
        $tempQuery = $productRepository->findMore($minPrice, $maxPrice, $cat, $word);
        $pageSize = 8;
        $paginator = new Paginator($tempQuery);
        $totalItems = count($paginator);

        $numberOfPages = ceil($totalItems / $pageSize);

        $tempQuery = $paginator->getQuery()->setFirstResult($pageSize * ($pageId - 1))->setMaxResults($pageSize);
        $products = $tempQuery->getResult();

            return $this->render('product/index.html.twig', [
                'products' => $products,
                'cat' => $cat,
                'categories' => $categoryRepository->findAll(),
                'numOfPages' => $numberOfPages,
                'word' => $word,
                'min' => $minPrice,
                'max' => $maxPrice,
            ]);
        
    }

/**
     * @Route("/addCart/{id}", name="app_add_cart", methods={"GET"})
     */
    public function addCart(Product $product, Request $request)
    {
        $session = $request->getSession();
        $quantity = (int)$request->query->get('quantity');

        //check if cart is empty
        if (!$session->has('cartElements')) {
            //if it is empty, create an array of pairs (prod Id & quantity) to store first cart element.
            $cartElements = array($product->getId() => $quantity);
            //save the array to the session for the first time.
            $session->set('cartElements', $cartElements);
        } else {
            $cartElements = $session->get('cartElements');
            //Add new product after the first time. (would UPDATE new quantity for added product)
            $cartElements = array($product->getId() => $quantity) + $cartElements;
            //Re-save cart Elements back to session again (after update/append new product to shopping cart)
            $session->set('cartElements', $cartElements);
        }
        return $this->redirectToRoute('app_product_show', ['id'=> $product->getId()], Response::HTTP_SEE_OTHER);

    }

    // /**
    // * @Route("/reviewCart", name="app_review_cart", methods={"GET"})
    // */
    // public function reviewCart(Request $request): Response
    // {
    //     $session = $request->getSession();
    //     if ($session->has('cartElements')) {
    //         $cartElements = $session->get('cartElements');
    //     } else
    //         $cartElements = [];
    //     return $this->json($cartElements);
    // }

    /**
    * @Route("/reviewCart", name="app_review_cart", methods={"GET"})
    */
    public function cart(Request $request, ProductRepository $productRepository){
        $total = 0;
        $session = $request->getSession();
        $cart = $session->get('cartElements',[]);
        $cartWithData = [];
        foreach ($cart as $id => $quantity){
            $cartWithData[] = [
                'product' => $productRepository->find($id),
                'quantity' => $quantity
            ];
        }
        foreach ($cartWithData as $item){
            $totalItem = $item['product']->getPrice() * $item['quantity'];
            $total += $totalItem;
        }
        return $this->render('cart/cart.html.twig',[
            'items' => $cartWithData,
            'total' => $total
        ]);
    }

    /**
    * @Route("/checkoutCart", name="app_checkout_cart", methods={"GET"})
    */
    public function checkoutCart(Request               $request,
    OrderDetailRepository $orderDetailRepository,
    OrderRepository       $orderRepository,
    ProductRepository     $productRepository,
    ManagerRegistry       $mr): Response
    {
    $this->denyAccessUnlessGranted('ROLE_USER');
    $entityManager = $mr->getManager();
    $session = $request->getSession(); //get a session
    // check if session has elements in cart
    if ($session->has('cartElements') && !empty($session->get('cartElements'))) {
    try {
    // start transaction!
    $entityManager->getConnection()->beginTransaction();
    $cartElements = $session->get('cartElements');

    //Create new Order and fill info for it. (Skip Total temporarily for now)
    $order = new Order();
    date_default_timezone_set('Asia/Ho_Chi_Minh');
    $order->setPurchaseDate(new \DateTime());
    /** @var \App\Entity\User $user */
    $user = $this->getUser();
    $order->setUser($user);
    $orderRepository->add($order, true); //flush here first to have ID in Order in DB.

    //Create all Order Details for the above Order
    $total = 0;
    foreach ($cartElements as $product_id => $quantity) {
    $product = $productRepository->find($product_id);
    //create each Order Detail
    $orderDetail = new OrderDetail();
    $orderDetail->setOrders($order);
    $orderDetail->setProduct($product);
    $orderDetail->setQuantity($quantity);
    $orderDetailRepository->add($orderDetail);

    $total += $product->getPrice() * $quantity;
    }
    $order->setTotal($total);
    $orderRepository->add($order);
    // flush all new changes (all order details and update order's total) to DB
    $entityManager->flush();

    // Commit all changes if all changes are OK
    $entityManager->getConnection()->commit();

    // Clean up/Empty the cart data (in session) after all.
    $session->remove('cartElements');
    } catch (Exception $e) {
    // If any change above got trouble, we roll back (undo) all changes made above!
    $entityManager->getConnection()->rollBack();
    }
    return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    } else
    return new Response("Shopping Cart has no product, please add some!");
    }

    /**
     * @Route("/new", name="app_product_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProductRepository $productRepository): Response
    {   
        
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        $checkUser = $this->isGranted('ROLE_SELLER');
        if (!$checkUser)
        {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }        
        

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var \App\Entity\User $user */
            $user = $this->getUser();
            $product->setPublisher($user);
            $productImage = $form->get('Image')->getData();
            if ($productImage) {
                $originExt = pathinfo($productImage->getClientOriginalName(), PATHINFO_EXTENSION);
                $productRepository->add($product, true);
                $newFilename = $product->getId() . '.' . $originExt;

                try {
                    $productImage->move(
                        $this->getParameter('product_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $product->setImgurl($newFilename);
            $productRepository->add($product, true);

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        
            }
        }
        return $this->renderForm('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_product_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Product $product, ProductRepository $productRepository): Response
    {   
        $checkUser = $this->isGranted('ROLE_SELLER');
        /** @var \App\Entity\User $user */
        $user = $this->getUser();
        if (!($checkUser && $user->getId() == $product->getPublisher()->getId()))
        {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $productImage = $form->get('Image')->getData();
            if ($productImage) {
                $originExt = pathinfo($productImage->getClientOriginalName(), PATHINFO_EXTENSION);
                $productRepository->add($product, true);
                $newFilename = $product->getId() . '.' . $originExt;

                try {
                    $productImage->move(
                        $this->getParameter('product_directory'),
                        $newFilename
                    );

WEBG301-ASM-master/templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

WEBG301-ASM-master/templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

WEBG301-ASM-master/templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <div class="container">
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}
    </br>
    <a href="{{ path('app_product_index') }}" class="btn btn-warning">Back to list</a>
    </br></br>
    {{ include('product/_delete_form.html.twig') }}
    </div>
{% endblock %}

WEBG301-ASM-master/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product Page{% endblock %}

{% block body %}
	<div class="container-md">
		<div class="row">
			<div class="col-3">
				<form action={{ path('app_product_index') }} method="get">
					{% if word is null %}
					<input class="form-control" type="search" placeholder="Search" aria-label="Search" name="word">
					{% else %}
					<input class="form-control" type="search" value="{{ word }}" aria-label="Search" name="word">
					{% endif %}
					Category:
                        <select name="category">
                        <option value="">All</option>
                        {% for category in categories %}
                        {% if category.id == cat %}
                        <option value="{{ category.id }}" selected >{{category.Name}}</option>
                        {% else %}
                        <option value="{{ category.id }}" >{{category.Name}}</option>
                        {% endif %}
                        {% endfor %}
                        </select><br>
				Min Price:
				{% if min is null %}
				<input type="number" name="minPrice"><br>
				{% else %}
				<input type="number" name="minPrice" value="{{ min }}"><br>
				{% endif %}
				Max Price:
				{% if max is null %}
				<input type="number" name="maxPrice"><br>
				{% else %}
				<input type="number" name="maxPrice" value="{{ max }}"><br>
				{% endif %}
				<input type="submit" value="Filter" class="btn btn-primary">
				|
				<a href="{{ path('app_product_index') }}" class="btn btn-primary">Reset</a>
				|
				<a href="{{ path('app_product_new') }}" class="btn btn-primary">Create New </a>
			</form>
		</div>
		<div class="col-9">
			<div class="container">
				<h4>Product Listing</h4>
				<div class="row row-cols-1 row-cols-md-4 g-4">
					{% for product in products %}
						<div class="col">
							<div class="card h-100">
								<img src=" {{ asset('images/product/' ~ product.imgurl) }}" class="card-img-top" alt="Not Found">
								<div class="card-body">
									<h5 class="card-title">{{ product.Name }}</h5>
									<h6 class="card-subtitle">Category:
										{{ product.category.Name }}</h6>
									<p>Price:
										{{ product.price }} $</p>
									<p>Seller:
										{{ product.publisher.name }}</p>
								</div>
								<div class="card-footer">
									<a href="{{ path('app_product_show', {'id': product.id}) }}" class="btn btn-primary">Show</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-2">
		<div style="display:flex;text-align:center;justify-content:center">
			<nav aria-label="Page navigation">
				<ul class="pagination">
					{% for i in range(1, numOfPages) %}
						{% set style = app.request.get('pageId')==i ? "active" : "" %}
						<li class="page-item {{ style }}">
							<a class="page-link" href={{ path(app.request.attributes.get('_route'), app.request.query.all|merge({'pageId': i} )) }}>{{ i }}</a>
						</li>
					{% endfor %}
					</ul>
				</nav>
			</div>
		</div>
	{% endblock %}

WEBG301-ASM-master/templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <div class="container">
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}
    </br>
    <a href="{{ path('app_product_index') }}" class="btn btn-warning">Back to list</a>
    </div>
{% endblock %}

WEBG301-ASM-master/templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-3 mb-4">
            <div class="col-md-4">
                <img src="{{ asset('images/product/' ~ product.imgurl) }}" alt="{{ product.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h1 class="mt-4 mt-md-0">{{ product.name }}</h1>
                <h2>{{ product.price }} $</h2>
                <hr>
                <p><b>Description: </b>{{ product.description }} </p>
                <p><b>Seller: </b> {{ product.publisher.name }} </p>
                {% if app.user %}
                <form action={{ path('app_add_cart',{ 'id': product.id }) }} method="get" class="mt-4 p-4 bg-light">
                    <div class="form-group">
                        <label for="quantity">Quantity</label>
				        <input type="number" name="quantity" placeholder="Amount"/>
                    </div>

                    <input type="submit" class="btn btn-warning" value="Add to Cart">
                </form>
                {% endif %}
                <a href="{{ path('app_product_index') }}" class="btn btn-warning">Back to list</a>
                {% if product.publisher == app.user %}
                <a href="{{ path('app_product_edit', {'id': product.id}) }}" class="btn btn-warning">Edit</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}