WEBG301-ASM-master/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $Category;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="Product")
     */
    private $orderDetails;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Imgurl;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="products")
     */
    private $Publisher;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setProduct($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getProduct() === $this) {
                $orderDetail->setProduct(null);
            }
        }

        return $this;
    }

    public function getImgurl(): ?string
    {
        return $this->Imgurl;
    }

    public function setImgurl(string $Imgurl): self
    {
        $this->Imgurl = $Imgurl;

        return $this;
    }

    public function getPublisher(): ?User
    {
        return $this->Publisher;
    }

    public function setPublisher(?User $Publisher): self
    {
        $this->Publisher = $Publisher;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

}

WEBG301-ASM-master/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"Email"}, message="There is already an account with this Email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $Email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $PhoneNum;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="User")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="Publisher")
     */
    private $products;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->Email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->Email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPhoneNum(): ?string
    {
        return $this->PhoneNum;
    }

    public function setPhoneNum(string $PhoneNum): self
    {
        $this->PhoneNum = $PhoneNum;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setPublisher($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getPublisher() === $this) {
                $product->setPublisher(null);
            }
        }

        return $this;
    }
}

WEBG301-ASM-master/templates/_footer.html.twig
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">© 2022 WebG301 - ASM, Khang - Khanh - Tien</p>

        <a href="/"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{{ path('app_index') }}" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="{{ path('app_about_us') }}" class="nav-link px-2 text-muted">About</a></li>
        </ul>
    </footer>
</div>

WEBG301-ASM-master/templates/_nav.html.twig
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="{{ path('app_index') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-4">Web Project</span>
        </a>
        

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{{ path('app_product_index') }}" class="nav-link">Products</a></li>
            <li class="nav-item"><a href="{{ path('app_about_us') }}" class="nav-link">About Us</a></li>
            {% if app.user %}
                <li class="nav-item"><a class="nav-link">Hello {{ app.user.email }}</a></li>
            {% endif %}
            <li class="nav-item">
                <a href="/{{ app.user ? 'logout' : 'login' }}" class="nav-link">
                    {{ app.user ? 'Logout' : 'Login' }}
                </a>
            </li>
            <li class="nav-item">
            <a href="{{ path('app_review_cart') }}" class="nav-link">Show Cart</a></li>
            </li>
            <li class="nav-item">
            <a href="{{ path('app_checkout_cart') }}" class="nav-link">Check out Cart</a></li>
        </ul>
    </header>
</div>

WEBG301-ASM-master/templates/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home Page{% endblock %}

{% block body %}
  <div class="container">
    <div class="container">
        <h1>About Us</h1>
    </div>
    <div class="container">
      <div class="container">
        <h3 class="about">Our team consists of 3 members </h3>
        <ul>
          <li><h4 class="about_us_dev_info">Truong Van Phuc Khang (Team Leader)</h4></li>
          <li><h4 class="about_us_dev_info">Tong Viet Tien</h4></li>
          <li><h4 class="about_us_dev_info">Nguyen Manh Ngoc Khanh</h4></li>
      </div>
      <div class="container">
        <p>This website is a web project that created by our group.
        This project can be used for education purpose.
        Feel free to download and change things as you like.</p>
        <p>According to statistics in 2022, the market condition is expanding again after the pandemic,
         and the newest numbers show that the number of individuals shopping for electronics such as phones and computers is increasing.
          Understanding this, we planned and designed an e-commerce project relating to electronic gadgets, which is a website that sells phones and computers,
          and items are mostly focused on authentic goods from major companies such as iPhone, ASUS, and so on, via a website distribution channel. Our sales website is called KKT,
          and we want to be able to recreate the business model in order to deliver the greatest products to users.</p>
    </div>
{% endblock %}

WEBG301-ASM-master/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
            crossorigin="anonymous">
    {{ encore_entry_link_tags('app') }}
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    {{ encore_entry_script_tags('app') }}
{% endblock %}

    </head>
    <body>
{{ include('_nav.html.twig') }}
{% block body %}{% endblock %}
{{ include('_footer.html.twig') }}
    </body>
</html>

WEBG301-ASM-master/templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home Page{% endblock %}

{% block body %}
    <div class="container-md">
        <h4>Page listing</h4>
		<ul>
            <li><a href="{{ path('app_product_index') }}" class="btn btn-light">Products</a></li>
            <li><a href="{{ path('app_about_us') }}" class="btn btn-light">About Us</a></li>
        </ul>
        <div class="col-9">
			<div class="container">
				<h4>Product Listing</h4>
				<div class="row row-cols-1 row-cols-md-4 g-4">
					{% for product in products %}
						<div class="col">
							<div class="card h-100">
								<img src=" {{ asset('images/product/' ~ product.imgurl) }}" class="card-img-top" alt="Not Found">
								<div class="card-body">
									<h5 class="card-title">{{ product.Name }}</h5>
									<h6 class="card-subtitle">Category:
										{{ product.category.Name }}</h6>
									<p>Price:
										{{ product.price }}</p>
								</div>
								<div class="card-footer">
									<a href="{{ path('app_product_show', {'id': product.id}) }}" class="btn btn-primary">Show</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
        </div>   
    </div>
{% endblock %}